name: My Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run Commands
      run: |
        cd /var/www
        git clone https://github.com/charlesgohck/potfolioblogv2.git
        cd potfolioblogv2
        npm install
        npm run build
