name: Deploy Portfolio Blog workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Delete existing folder
      run: |
        rm -rf /home/charlesgohck/portfolioblogv2
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install dependencies for application
      run: |
        cd /home/charlesgohck/portfolioblogv2
        npm install
    - name: Build application
      run: |
        npm run build
    - name: Deploy application on port 443
      run: |
        npm run start -- -p 443
