name: Deploy Portfolio Blog workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Code v3
      uses: actions/checkout@v3
    - name: Delete Existing Folder if Present
      run: |
        rm -rf /home/charlesgohck/portfolioblogv2
    - name: Clone Repository
      run: |
        git clone git@github.com:charlesgohck/portfolioblogv2.git
    - name: Install Dependencies
      run: |
        cd /home/charlesgohck/portfolioblogv2
        npm install
    - name: Build Application
      run: |
        npm run build
    - name: Deploy Application On Port 443
      run: |
        npm run start -- -p 443
