name: Deploy Portfolio Blog workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Code v3
      uses: actions/checkout@v3
    - name: Delete Existing Folder if Present
      run: |
        rm -rf /home/project-enterprise/portfolioblogv2
    - name: Clone Repository
      run: |
        git clone -c core.sshCommand="ssh -i ~/.ssh/id_ed25519_project_enterprise_github_actions" git@github.com:charlesgohck/portfolioblogv2.git /home/project-enterprise/portfolioblogv2
    - name: Change Directory to Correct Directory
      run: |
        cd /home/project-enterprise/portfolioblogv2
    - name: Archive old log files if they exist
      run: |
        if [ -f /home/project-enterprise/project_enterprise_log.log ]; then mv -n /home/project-enterprise/project_enterprise_log.log project_enterprise_log_$(date +%Y-%m-%d_%H-%M-%S).log; fi
    - name: Install Dependencies, Build Application, Deploy on Port 443
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh
        npm install
        npm run build
        npm run start -- --p 443 >> /home/project-enterprise/project_enterprise_log.log 2>&l &
